### ISSUE TITLE
部分页面proform组件,request方法可能导致渲染数据不同步

### ISSUE THREAD

**Issue by Ryan-CW-Code** [whiteshader/Ruoyi-React#3]
![image](https://github.com/whiteshader/Ruoyi-Cloud-React-Admin/assets/75795462/44520765-a64d-4108-9019-4bb40e7eec40)
如图所示，如果 menuTree 的值在组件挂载时还没有被设置，会导致tree为空。并且不是每次menuTree修改都会触发ProFormSelect 的request远程请求函数.
导致页面无法显示数据，尝试更改为下图所示，主要时保证了menuTree修改时都会触发ProFormSelect更新。目前此问题没有复现过了，因为代码别的地方也有很多适配项目修改就不提PR了
![image](https://github.com/whiteshader/Ruoyi-Cloud-React-Admin/assets/75795462/71f00085-4e98-4f71-8973-c764a3c56dd0)
**凡是使用request返回props消息的都有此问题。**

**Comment by Ryan-CW-Code** [comment]
还有一个体验不好的地方，后台所有接口返回的都是200，错误信息是放在响应载荷里面。
但是接口没有对响应载荷code字段进行判断，导致所有接口请求都是成功，但是有些添加数据的时候后台返回的是错误信息，前端却无法捕捉，提示信息是添加成功，实际没有成功，体验很不好。
我目前在全局请求response里面判断返回数据code是否为200，不为200就抛出错误，让try捕捉。这个实现并不好，期待作者官方实现

**Comment by Ryan-CW-Code** [comment]
代码生成页面，编辑按钮路由提示404，需要在路由配置信息中添加/tool/gen/edit的路由

**Comment by whiteshader** [comment]
menuTree 数据是在index.tsx的table request初始化，edit 在没有数据时是不会进入的，edit后会reload，不存在不同步的时候
