### ISSUE TITLE
本地运行前端工程 接口调用正常 部署到docker 运行接口调用异常

### ISSUE THREAD

**Issue by HsiYang506** [whiteshader/Ruoyi-React#5]
[
<img width="874" alt="微信图片_20231009115041" src="https://github.com/whiteshader/React-Admin-Cloud/assets/19218795/c55336d1-d2f0-4dbf-9809-2417b8e100ff">
<img width="883" alt="微信图片_20231009115055" src="https://github.com/whiteshader/React-Admin-Cloud/assets/19218795/4b3ce765-4ee5-429c-8643-bff1e31b1e22">
](url)

**Comment by 404area** [comment]
应该是跨域的问题，自行排查一下

**Comment by whiteshader** [comment]
nginx代理搞一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月13日 14:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [whiteshader/React-Admin-Cloud] 本地运行前端工程 接口调用正常 部署到docker 运行接口调用异常 (Issue #5) |

应该是跨域的问题，自行排查一下
